### PR TITLE
Mnlbox big auth refactor

### PR DESCRIPTION
**Pull request by elitan**
Can I do this? Not too much experience with this.. Learning tho!!

### CODE REVIEW

**Comment by elitan** [comment]
That should be it. Going to bed. Need to take a new look at this with fresh eyes.

**Comment by mnlbox** [comment]
@elitan Why we need separate PR when we have #24 :thinking:  :smiley:

**Comment by elitan** [comment]
I did not know how to push to that repo/branch :/

**Comment by elitan** [comment]
But I think it works really good now! 👍

**Pull request merged**
