### PR TITLE
WIP: Add nuxt example

### PR DESCRIPTION
**Pull request by MarcelloTheArcane**
Here's an example I've made for using hasura backend plus with Nuxt.

### CODE REVIEW

**Comment by MarcelloTheArcane** [comment]
This doesn't implement [nuxt-auth-refresh](https://github.com/haosx86/nuxt-auth-refresh) yet.

**Comment by elitan** [comment]
Awesome work! Let me know if you need any help from me.

**Comment by MarcelloTheArcane** [comment]
@elitan It looks like nuxt-auth module has [just added support for refresh tokens](https://github.com/nuxt-community/auth-module/pull/361/files)! 

Let me test it out tomorrow, and this could be good to go without the nuxt-auth-refresh above.

**Comment by MarcelloTheArcane** [comment]
@elitan This is probably good to go - what do you reckon?

**Comment by elitan** [comment]
Great work!

**Pull request merged**
